import type { BuildWithProofPackedReturnTypeParameters, BuildWithProofPackedReturnType, ParseTFHEProvenCompactCiphertextListParameters, ParseTFHEProvenCompactCiphertextListReturnType, SerializeGlobalFheCrsParameters, SerializeGlobalFheCrsReturnType, SerializeGlobalFhePkeParamsParameters, SerializeGlobalFhePkeParamsReturnType, SerializeGlobalFhePublicKeyParameters, SerializeGlobalFhePublicKeyReturnType, EncryptModuleFactory, DeserializeGlobalFhePublicKeyParameters, DeserializeGlobalFhePublicKeyReturnType, DeserializeGlobalFheCrsParameters, DeserializeGlobalFheCrsReturnType } from "./types.js";
export declare function parseTFHEProvenCompactCiphertextList(_parameters: ParseTFHEProvenCompactCiphertextListParameters): Promise<ParseTFHEProvenCompactCiphertextListReturnType>;
export declare function buildWithProofPacked(_parameters: BuildWithProofPackedReturnTypeParameters): Promise<BuildWithProofPackedReturnType>;
export declare function serializeGlobalFhePkeParams(_parameters: SerializeGlobalFhePkeParamsParameters): Promise<SerializeGlobalFhePkeParamsReturnType>;
export declare function serializeGlobalFhePublicKey(_parameters: SerializeGlobalFhePublicKeyParameters): Promise<SerializeGlobalFhePublicKeyReturnType>;
export declare function serializeGlobalFheCrs(_parameters: SerializeGlobalFheCrsParameters): Promise<SerializeGlobalFheCrsReturnType>;
export declare function deserializeGlobalFheCrs(_parameters: DeserializeGlobalFheCrsParameters): Promise<DeserializeGlobalFheCrsReturnType>;
export declare function deserializeGlobalFhePublicKey(_parameters: DeserializeGlobalFhePublicKeyParameters): Promise<DeserializeGlobalFhePublicKeyReturnType>;
export declare const encryptActions: EncryptModuleFactory;
//# sourceMappingURL=mock.d.ts.map