// Tricky: should be improved
// ==========================
// The current project settings do not support trivial type declarations shared between
// a standalone .d.ts like global.d.ts and a generated .d.ts file (generated by the tsc compiler)
// Consequently, we must define both files manually:
// - tfhe_tkms_types.ts
// - tfhe_tkms_types.d.ts
// to satisfy both import cases: import in a .ts file and import in a .d.ts file
// If not either: 
// - api-extractor raises an error
// or 
// - TFHEType is not exported resulting in future tsc compile error each time relayer-sdk is imported.

export type TFHEType = {
  default?: any;
  TFHEInput?: any;
  TfheCompactPublicKey: any;
  CompactPkeCrs: any;
  initThreadPool?: any;
  init_panic_hook: any;
  CompactCiphertextList: any;
  ZkComputeLoad: any;
};

export type TKMSType = {
  default?: any;
  u8vec_to_ml_kem_pke_pk: any;
  u8vec_to_ml_kem_pke_sk: any;
  new_client: any;
  new_server_id_addr: any;
  process_user_decryption_resp_from_js: any;
  ml_kem_pke_keygen: any;
  ml_kem_pke_pk_to_u8vec: any;
  ml_kem_pke_sk_to_u8vec: any;
  ml_kem_pke_get_pk: any;
};
