// Tricky: should be improved
// ==========================
// The current project settings do not support trivial type declarations shared between
// a standalone .d.ts like global.d.ts and a generated .d.ts file (generated by the tsc compiler)
// Consequently, we must define both files manually:
// - tfheType.ts
// - tfheType.d.ts
// to satisfy both import cases: import in a .ts file and import in a .d.ts file
// If not either:
// - api-extractor raises an error
// or
// - TFHEType is not exported resulting in future tsc compile error each time relayer-sdk is imported.

export type TFHEType = {
  default?: any;
  TFHEInput?: any;
  TfheCompactPublicKey: any;
  CompactPkeCrs: any;
  initThreadPool?: any;
  init_panic_hook: any;
  CompactCiphertextList: any;
  ZkComputeLoad: any;
};
